### ISSUE TITLE
Allow setting custom navigation key

### ISSUE THREAD

**Issue by kuhnroyal** [gurleensethi/sailor#12]
It would be great if we could set a custom `GlobalKey<NavigatorState> navigatorKey` which defaults to the existing one if not provided. This would make it easier to integrate Sailor with other libraries that also rely on the navigator key.

**Comment by gurleensethi** [comment]
Hi @kuhnroyal 
I am happy to let you know that Sailor `v0.6.0` now supports passing a custom `navigatorKey`.
You can achieve this by using `SailorOptions`.
```dart
Sailor(
  options: SailorOptions(
    navigatorKey: <your_navigator_key>
  ),
)
```
Looking for more feature requests.
