### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by ghost** [gurleensethi/sailor#36]
Hi, 

Can I use this package to ship a product? Awesome package btw.

**Comment by haqqi** [comment]
I have uses this for one of my production app. And it works well. I don't know whether this will be continued or not.

**Comment by elhe26** [comment]
It seems the maintainer is not active.

**Comment by haqqi** [comment]
@elhe26 Seems so. I already released the production 3 months ago. But this is github community. We can fork and fixed the deprecated functionality.

**Comment by gurleensethi** [comment]
@haqqi Yes its production ready, sorry for the delay. I will keep the project updated as required.

**Comment by haqqi** [comment]
Wow, thanks for appearing @gurleensethi.

This sailor library is really awesome and easily used. I have several issues of improvements, and post it if you decide to continue it.
