### ISSUE TITLE
Error in 0.7.0

### ISSUE THREAD

**Issue by jonny7737** [gurleensethi/sailor#41]
Compiler message:
../../dev-tools/flutter/.pub-cache/hosted/pub.dartlang.org/sailor-0.7.0/lib/src/sailor.dart:429:43: Error: Can't return a value from a void function.
    return this.navigatorKey.currentState.pop(result);
                                                                         ^

Build fails.

**Comment by gurleensethi** [comment]
@jonny7737 Fixed in `0.7.1`. Please check. Let me know of any other issue of features.
