### ISSUE TITLE
How do i use popUntil function?

### ISSUE THREAD

**Issue by chounry** [gurleensethi/sailor#45]
No description

**Comment by YouSour** [comment]
i want to know too , in document don't show how to use it @chounry have you found it yet ?

**Comment by chounry** [comment]
> i want to know too , in document don't show how to use it @chounry have you found it yet 

`.sailor.popUntil(ModalRoute.withName('Route-name'))`

**Comment by YouSour** [comment]
thank you @chounry , how about pop function ?

**Comment by YouSour** [comment]
thank you @chounry , by the way you should close this issue. 😄
